# Generated by Django 4.0.2 on 2022-04-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_image', models.ImageField(upload_to='')),
                ('source_image', models.ImageField(upload_to='')),
                ('result_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
