# Generated by Django 4.0.2 on 2022-04-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_outputimage_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputimage',
            name='source_image',
            field=models.ImageField(upload_to='main/files/source'),
        ),
        migrations.AlterField(
            model_name='inputimage',
            name='style_image',
            field=models.ImageField(upload_to='main/files/style'),
        ),
        migrations.AlterField(
            model_name='outputimage',
            name='result_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/files/result'),
        ),
    ]
