# Generated by Django 4.0.2 on 2022-04-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_testimage_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_images', models.ImageField(upload_to='orpage/result')),
            ],
        ),
    ]
